### ISSUE TITLE
Updating of aircraft positioning

### ISSUE THREAD

**Issue by doyle-mark** [vatsimnetwork/dataserver#28]
Hey there! 

I am very much enjoying using the new json datafeed. However, I am creating a vatsim map and doing some interpolation and predictive rendering and I was wondering if there was a fixed number for how often the position of an aircraft is updated? 

Best, Mark

**Comment by nepetadosmil** [comment]
Hey Mark! Aircraft report their positions every 5 seconds, but the datafile is updated every 15 seconds, so that's more or less the time difference between updates you'll see.

**Comment by doyle-mark** [comment]
thanks Nestor, that's very useful, cheers!
